import openai
import os


class openai_chat_gpt:
    """
    This class represents the brain API for interacting with the GPT-3.5-turbo model.
    """

    def __init__(self,api_key=None,MAX_TOKEN=4096,temperature=0,model="gpt-3.5-turbo-0613"):
        """
        Initializes the brain API with the OpenAI API key.
        """
        self.api_key = api_key
        self.model = model
        self.MAX_TOKEN = MAX_TOKEN
        self.temperature = temperature
        if api_key is not None:
            openai.api_key = self.api_key
        
    def get_completion_for_message(self, message, temperature=None):
        """
        Generates a completion for a given message using the GPT-3.5-turbo model.

        Args:
            message (list): List of messages representing the conversation history.
            temperature (float): Control the randomness of the output.

        Returns:
            str: The completion generated by the model.
            int: The number of tokens used by the completion.
        """
        if temperature is None:
            temperature = self.temperature
        completion = openai.ChatCompletion.create(
            model=self.model,
            messages=message,
            temperature=temperature
        )
        return completion.choices[0].message['content'], completion['usage']['prompt_tokens']
    
    
    